=== Ericsson-LMF/IoT-Gateway/osgi/serviceschema.xmlparser/src/main/xsd/services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://xmlparser.service.deviceaccess.ericsson.com"
           xmlns="http://xmlparser.service.deviceaccess.ericsson.com">

    <xs:element name="service-schema">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="services"/>
            </xs:sequence>
            <xs:attribute name="version" use="required" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="services">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="service"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="service">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:element ref="category"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="actions"/>
                    <xs:element ref="properties"/>
                </xs:sequence>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="category" type="xs:NCName"/>
    <xs:element name="actions">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="action"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="action">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:sequence minOccurs="0">
                    <xs:element ref="arguments"/>
                    <xs:element ref="results"/>
                </xs:sequence>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="optional" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="arguments">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="parameter"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="results">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="parameter"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="properties">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="parameter"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="parameter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description"/>
                <xs:choice>
                    <xs:element ref="values"/>
                    <xs:sequence>
                        <xs:element ref="min"/>
                        <xs:element ref="max"/>
                    </xs:sequence>
                </xs:choice>
                <xs:element minOccurs="0" ref="default"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="values">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="value"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="value" type="xs:NCName"/>
    <xs:element name="min" type="xs:decimal"/>
    <xs:element name="max" type="xs:decimal"/>
    <xs:element name="default" type="xs:NMTOKEN"/>
</xs:schema>

=== Ericsson-LMF/IoT-Gateway/osgi/generic.device.access.services/src/main/resources/services.xml
<?xml version="1.0"?>
<service-schema xmlns="http://xmlparser.service.deviceaccess.ericsson.com"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://www.cf.ericsson.net/schema/services.xsd"
                version="1.0.0">
    <services>
        <!-- Generic -->
        <service name="DeviceManagement">
            <description>This service type enables altering parameters on the device.</description>
            <category>device</category>
            <actions>
                <action name="setName">
                    <description>Sets the name on the device.</description>
                    <arguments>
                        <parameter name="newName" type="String">
                            <description>The new name.</description>
                        </parameter>
                    </arguments>
                </action>
                <action name="setURN">
                    <description>Sets the URN on the device.</description>
                    <arguments>
                        <parameter name="newURN" type="String">
                            <description>The new URN.</description>
                        </parameter>
                    </arguments>
                </action>
            </actions>
        </service>

        <!-- Home Automation -->
        <service name="TemperatureSensor">
            <description>This service type enables reading of the current temperature of a temperature sensor
            </description>
            <category>homeautomation.hvac</category>
            <properties>
                <parameter name="currentTemperature" type="Float">
                    <description>The current temperature. Unit: degrees Celsius</description>
                </parameter>
            </properties>
        </service>

        <service name="ThermostatMode">
            <category>homeautomation.hvac.thermostat</category>
            <description>This service provides access the mode of a thermostat.</description>
            <properties>
                <parameter name="mode" type="String">
                    <description>The current mode of the thermostat.</description>
                    <default>Off</default>
                    <values>
                        <value>Off</value>
                        <value>Heat</value>
                        <value>Cool</value>
                        <value>Auto</value>
                        <value>AuxilliaryHeat</value>
                        <value>Resume</value>
                        <value>FanOnly</value>
                        <value>Furnace</value>
                        <value>DryAir</value>
                        <value>MoistAir</value>
                        <value>AutoChangeover</value>
                        <value>EnergySaveHeat</value>
                        <value>EnergySaveCool</value>
                        <value>Away</value>
                    </values>
                </parameter>
            </properties>
            <actions>
                <action name="setMode">
                    <description>Sets the thermostat mode.</description>
                    <arguments>
                        <parameter name="mode" type="String">
                            <description>The thermostat mode. Unit: degrees Celsius</description>
                            <default>Off</default>
                            <values>
                                <value>Off</value>
                                <value>Heat</value>
                                <value>Cool</value>
                                <value>Auto</value>
                                <value>AuxilliaryHeat</value>
                                <value>Resume</value>
                                <value>FanOnly</value>
                                <value>Furnace</value>
                                <value>DryAir</value>
                                <value>MoistAir</value>
                                <value>AutoChangeover</value>
                                <value>EnergySaveHeat</value>
                                <value>EnergySaveCool</value>
                                <value>Away</value>
                            </values>
                        </parameter>
                    </arguments>
                </action>
            </actions>
        </service>

        <service name="ThermostatFanMode">
            <category>homeautomation.hvac.thermostat</category>
            <description>This service provides access to fan of a thermostat.</description>
            <properties>
                <parameter name="currentFanMode" type="Float">
                    <description>The current fan mode.</description>
                    <values>
                        <value>Auto</value>
                        <value>AutoLow</value>
                        <value>AutoMedium</value>
                        <value>AutoHigh</value>
                        <value>On</value>
                        <value>Low</value>
                        <value>Medium</value>
                        <value>High</value>
                    </values>
                </parameter>
            </properties>
            <actions>
                <action name="setFanMode">
                    <description>Sets the fan mode.</description>
                    <arguments>
                        <parameter name="fanMode" type="Float">
                            <description>The fan mode.</description>
                            <values>
                                <value>Auto</value>
                                <value>AutoLow</value>
                                <value>AutoMedium</value>
                                <value>AutoHigh</value>
                                <value>On</value>
                                <value>Low</value>
                                <value>Medium</value>
                                <value>High</value>
                            </values>
                        </parameter>
                    </arguments>
                </action>
            </actions>
        </service>

        <service name="ThermostatSetPoint">
            <category>homeautomation.hvac.thermostat</category>
            <description>This service provides access to the setpoint of a thermostat.</description>
            <properties>
                <parameter name="currentDesiredHeatingTemperature" type="Float">
                    <description>The current value of the desired heating temperature. Unit: degrees Celsius</description>
                </parameter>
                <parameter name="currentDesiredCoolingTemperature" type="Float">
                    <description>The current value of the desired cooling temperature. Unit: degrees Celsius</description>
                </parameter>
            </properties>
            <actions>
                <action name="setDesiredHeatingTemperature">
                    <description>Sets the desired heating temperature.</description>
                    <arguments>
                        <parameter name="desiredTemperature" type="Float">
                            <description>The desired temperature. Unit: degrees Celsius</description>
                            <default>20.0</default>
                        </parameter>
                    </arguments>
                </action>
                <action name="setDesiredCoolingTemperature">
                    <description>Sets the desired cooling temperature.</description>
                    <arguments>
                        <parameter name="desiredTemperature" type="Float">
                            <description>The desired temperature. Unit: degrees Celsius</description>
                            <default>20.0</default>
                        </parameter>
                    </arguments>
                </action>
            </actions>
        </service>

        <service name="LightSensor">
            <category>homeautomation</category>
            <description>A sensor which detects light.</description>
            <properties>
                <parameter name="light" type="Integer">
                    <description>The current luminence measured as a percentage 0=darkest, 100=lightest.</description>
                    <default>0</default>
                    <min>0</min>
                    <max>100</max>
                </parameter>
            </properties>
        </service>

        <service name="Dimming">
            <description>This service type enables the following functions: 1. Enables remote control of a dimmable
                lighting device, 2. Defines required basic actions for dimming to a value
            </description>
            <category>homeautomation.lighting</category>
            <actions>
                <action name="SetLoadLevelTarget">
                    <description>Sets the load level target, i.e. the dimming value.</description>
                    <arguments>
                        <parameter name="loadLevelTarget" type="Integer">
                            <description>The load level target. Unit: percentage 0-100%.</description>
                            <min>0</min>
                            <max>100</max>
                        </parameter>
                    </arguments>
                </action>
                <action name="SetLoadLevelTargetWithRate">
                    <description>Sets the load level target, i.e. the dimming value.</description>
                    <arguments>
                        <parameter name="loadLevelTarget" type="Integer">
                            <description>The load level target. Unit: percentage 0-100%.</description>
